config:
  # Path to the directory the ranks should be stored in
  db-path: "./ranks/"

  # If set to true pretty printing will be enabled
  db-pretty-print: true

  # Set the default rank players will receive the first time they join
  # default: ""

  # If set to false, no prefixes will be displayed
  use-prefix: true

  # If set to false, no suffixes will be displayed
  use-suffix: true

  # The format used for displaying prefixes
  prefix-format: "$prefix <gray>|</gray>"

  # The format used for displaying suffixes
  suffix-format: "<gray>|</gray> $suffix"

language:
  # Path to the languages database
  db: "./languages.yml"

  # The default language
  default: "english"